name: CICD
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t vuduc15/practice-cicd .
      - name: Publish image to docker Hub
        run: docker push vuduc15/practice-cicd:latest

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull image from docker Hub
        run: docker pull vuduc15/practice-cicd:latest
      - name: Delete Old Container
        run: docker rm -f reactContainer
      - name: Run docker container
        run: docker run -d -p 80:80 --name reactContainer vuduc15/practice-cicd

  noti:
    needs:
      - build
      - deploy
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Truncate Commit Message
        id: truncate_message
        run: |
          commit_message="${{ github.event.head_commit.message }}"
          truncated_commit_message=$(echo "$commit_message" | cut -c1-80)
          if [ ${#commit_message} -gt 80 ]; then
            truncated_commit_message="${truncated_commit_message}..."
          fi
          echo "TRUNCATED_COMMIT_MESSAGE=$truncated_commit_message" >> $GITHUB_ENV

      - name: Send Notification to Slack
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": ":white_check_mark: *Deployment Notification*",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ needs.build.result == 'failure' && ':x: *Build Failed!*' || needs.deploy.result == 'failure' && ':x: *Deploy Failed!*' || ':white_check_mark: *Deploy Successfully!*' }}"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Commit:*\n<${{ github.event.head_commit.url }}|${{ env.TRUNCATED_COMMIT_MESSAGE }}>"
                    }
                  ]
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Triggered by: <https://github.com/${{ github.actor }}|${{ github.actor }}> via push to *main*"
                    }
                  ]
                }
              ]
            }
