name: CICD
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t vuduc15/practice-cicd .
      - name: Publish image to docker Hub
        run: docker push vuduc15/practice-cicd:latest

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull image from docker Hub
        run: docker pull vuduc15/practice-cicd:latest
      - name: Delete Old Container
        run: docker rm -f reactContainer
      - name: Run docker container
        run: docker run -d -p 80:80 --name reactContainer vuduc15/practice-cicd

  noti:
    needs:
      - build
      - deploy
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Notify Success to Slack
        if: ${{ needs.build.result == 'success' && needs.deploy.result == 'success' }}
        uses: slackapi/slack-github-action@v2
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "✅ *Deploy Succeeded*"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Commit*: ${{ github.event.head_commit.message }}\n*Committer*: ${{ github.event.head_commit.author.name }}\n*Details*: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow>"
                  }
                }
              ]
            }
      - name: Notify Failure to Slack
        if: ${{ needs.build.result == 'failure' || needs.deploy.result == 'failure' }}
        uses: slackapi/slack-github-action@v2
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "❌ *Deploy Failed*"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Commit*: <${{ github.event.head_commit.url }}|${{ github.event.head_commit.message }}>\n*Committer*: ${{ github.event.head_commit.author.name }}\n*Details*: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow>"
                  }
                }
              ]
            }
