name: CICD
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t vuduc15/practice-cicd .
      - name: Publish image to docker Hub
        run: docker push vuduc15/practice-cicd:latest

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull image from docker Hub
        run: docker pull vuduc15/practice-cicd:latest
      - name: Delete Old Container
        run: docker rm -f reactContainer
      - name: Run docker container
        run: docker run -d -p 80:80 --name reactContainer vuduc15/practice-cicd

  noti:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Read Payload File
        id: read_payload
        run: |
          payload=$(<.github/slack_payload.json)
          echo "payload=$payload" >> $GITHUB_ENV

      - name: Post a message in a channel
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: ${{ env.payload }}
